<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="LAP-C-4153" name="testScripts.Cancellation_Outbound2" tests="7" failures="1" timestamp="04 Jul 2022 05:17:09 GMT" time="869.355" errors="0">
  <testcase name="OUT_Cancellation_DuringPartialpicking" time="270.746" classname="testScripts.Cancellation_Outbound2"/>
  <testcase name="OUT_Cancellation_pickgenerationScreen" time="200.448" classname="testScripts.Cancellation_Outbound2"/>
  <testcase name="OUT_Cancellation_atOrderisinDispatchDashboard" time="0.000" classname="testScripts.Cancellation_Outbound2">
    <skipped/>
  </testcase> <!-- OUT_Cancellation_atOrderisinDispatchDashboard -->
  <testcase name="OUT_Cancellation_atOrderisinConsolidationDashboard" time="196.371" classname="testScripts.Cancellation_Outbound2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testScripts.CommonFunctions.verify(CommonFunctions.java:956)
at testScripts.Cancellation_Outbound2.OUT_Cancellation_atOrderisinConsolidationDashboard(Cancellation_Outbound2.java:1231)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- OUT_Cancellation_atOrderisinConsolidationDashboard -->
  <testcase name="OUT_Cancellation_DuringPartialDispatch" time="0.000" classname="testScripts.Cancellation_Outbound2">
    <skipped/>
  </testcase> <!-- OUT_Cancellation_DuringPartialDispatch -->
  <testcase name="OUT_Cancellation_Orderisin_PickerDashboardScreen" time="201.790" classname="testScripts.Cancellation_Outbound2"/>
  <testcase name="OUT_Cancellation_DuringPartialconsolidation" time="0.000" classname="testScripts.Cancellation_Outbound2">
    <skipped/>
  </testcase> <!-- OUT_Cancellation_DuringPartialconsolidation -->
</testsuite> <!-- testScripts.Cancellation_Outbound2 -->
