<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAP-C-4153" name="testScripts.Site_Site" tests="2" failures="0" timestamp="16 May 2023 14:58:02 GMT" time="74.967" errors="2">
  <testcase name="endTest" time="0.063" classname="testScripts.Site_Site">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.io.File.<init>(Unknown Source)
at javax.activation.FileDataSource.<init>(Unknown Source)
at testScripts.ProjectSpecificFunctions.Email_trigger(ProjectSpecificFunctions.java:965)
at testScripts.ProjectSpecificFunctions.endTest(ProjectSpecificFunctions.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at testScripts.VisibilityMain.main(VisibilityMain.java:68)
]]>
    </error>
  </testcase> <!-- endTest -->
  <testcase name="fifosugPicktypeInb1" time="74.904" classname="testScripts.Site_Site">
    <error type="java.lang.Exception" message="(//td[@id=&#039;DashboardPO_GateInNum&#039;])[1] not found">
      <![CDATA[java.lang.Exception: (//td[@id='DashboardPO_GateInNum'])[1] not found
at testScripts.TestNGlisteners.onTestFailure(TestNGlisteners.java:62)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at testScripts.VisibilityMain.main(VisibilityMain.java:68)
]]>
    </error>
  </testcase> <!-- fifosugPicktypeInb1 -->
</testsuite> <!-- testScripts.Site_Site -->
